### ISSUE TITLE
Is selenium Framework for Swift ?

### ISSUE THREAD

**Issue by SheethalJossan** [appium/selenium-swift#3]
While using " pod 'Selenium' " we are getting Objective C Selenium Framework. So we need to bridge to use it.
Please give a reply.

**Comment by penguinho** [comment]
There is no swift version, but it should be easy to mix this library in to a swift project

**Comment by SheethalJossan** [comment]
Thank you so much. While using bridgingHeader, it's working fine. 

_import Selenium_

**Comment by tejasmanohar** [comment]
Can Selenium be run on iOS or is this just for Mac?

**Comment by Jonahss** [comment]
Selenium can only automate web browsers on a Mac. If you want to automate
iOS apps, Mac apps, or browsers on an iOS device, you can use Appium.
